### ISSUE TITLE
Atom-shell rename has broken requests pipeline

### ISSUE THREAD

**Issue by rcreasey** [joaomoreno/gulp-atom-shell#11]
They've renamed their repository, so all github api calls are now 404'ing for current and previous versions:

https://github.com/atom/electron/releases/tag/v0.24.0

https://api.github.com/repos/atom/atom-shell/releases

**Comment by joaomoreno** [comment]
Thanks for the heads up. But this has already been fixed. Please update to `0.6.0`.

**Comment by rcreasey** [comment]
Derp.  Good work :+1:
