### ISSUE TITLE
Unable to download latest electron package

### ISSUE THREAD

**Issue by yshrsmz** [joaomoreno/gulp-atom-shell#13]
this plugin tries to download `atom-shell-v0.25.0-darwin-x64.zip`, but its name is actually `electron-v0.25.0-darwin-x64.zip`

**Comment by joaomoreno** [comment]
please update to the latest version

**Comment by andornaut** [comment]
This appears to still attempt to download assetNames like 'atom-shell...zip':

[download.js#L55](https://github.com/joaomoreno/gulp-atom-shell/blob/master/src/download.js#L55)
```
var assetName = ['atom-shell', version, platform, arch].join('-') + '.zip';
```
Whereas electron release artifacts are named like "electron-v0.25.1-linux-x64.zip".
