### ISSUE TITLE
Update tests and documentation to refer to electron versions above 0.24.0

### ISSUE THREAD

**Issue by andornaut** [joaomoreno/gulp-atom-shell#16]
Please consider updating the tests and the example documentation to refer to a version of electron equal to or greater than v0.24.0.

This should help to avoid confusion due to the "atom-shell" to "electron" name change.

**Comment by joaomoreno** [comment]
Actually I want to "just make it work", no need for doc. But I'm currently
on vacation. There's already a pull request that almost fixes this,
although it  needs some work. Consider going there and help out!
