### ISSUE TITLE
MacOSX: "LSOpenURLsWithRole() failed with error -10810" when i use my custom productName

### ISSUE THREAD

**Issue by andycaramba** [joaomoreno/gulp-atom-shell#3]
If i set productName to 'Atom' or manually change MyApp.app/Contents/Info.plist
from
```
<key>CFBundleName</key>
<string>MyApp</string>
```
to
```
<key>CFBundleName</key>
<string>Atom</string>
```
It works ok.

I use Mac OS X 10.10 and atom-shell v0.20.0

**Comment by joaomoreno** [comment]
Given that, it really seems to be an issue in atom shell. Reopen, if I'm mistaken.
